// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: deaddrop/v1/deaddrop.proto

// DEAD DROP wire schema — the single source of truth for every type that crosses the
// gateway/bus boundary. Codegen targets: Go (gateway), PHP (control plane), TS (client).
//
// INVARIANT (brief §4.1): the server only ever sees opaque ciphertext. Nothing in this
// schema may carry plaintext content or a sender identity. `payload` is E2E ciphertext the
// server cannot read. There is no sender field — sender identity lives inside `payload`
// (sealed sender, implemented at M3). No field here may be persisted to disk (§5.10).

package deaddropv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	ErrorCode_ERROR_CODE_MALFORMED   ErrorCode = 1
	ErrorCode_ERROR_CODE_TOO_LARGE   ErrorCode = 2 // payload exceeds the max bucket
	ErrorCode_ERROR_CODE_RATE_LIMIT  ErrorCode = 3
	ErrorCode_ERROR_CODE_INTERNAL    ErrorCode = 4
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_MALFORMED",
		2: "ERROR_CODE_TOO_LARGE",
		3: "ERROR_CODE_RATE_LIMIT",
		4: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED": 0,
		"ERROR_CODE_MALFORMED":   1,
		"ERROR_CODE_TOO_LARGE":   2,
		"ERROR_CODE_RATE_LIMIT":  3,
		"ERROR_CODE_INTERNAL":    4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_deaddrop_v1_deaddrop_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_deaddrop_v1_deaddrop_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_deaddrop_v1_deaddrop_proto_rawDescGZIP(), []int{0}
}

// An opaque, server-uninterpretable message. The ONLY shape that crosses the bus.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Random, client-generated. Used for dedup and delete-on-delivery. Not derived from
	// content or identity.
	MessageId []byte `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Opaque per-recipient mailbox identifier. NOT an account id and NOT linkable to a
	// sender by the server. Routing key for fan-out only.
	RoutingKey string `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	// End-to-end ciphertext. Opaque to every server tier. At M3 the client pads this to a
	// fixed size bucket before it is sent, so length leaks nothing.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Transport-layer TTL backstop for undelivered ciphertext (§3.2). The real readability
	// lifetime is encoded INSIDE the encrypted payload and enforced client-side after
	// decryption; this is only how long the bus holds an undelivered blob before dropping it.
	TtlSeconds    uint32 `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_deaddrop_v1_deaddrop_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *Envelope) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// Client -> gateway.
type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientFrame_Subscribe
	//	*ClientFrame_Publish
	//	*ClientFrame_Ack
	//	*ClientFrame_SendOffer
	//	*ClientFrame_SendAccept
	Body          isClientFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_deaddrop_v1_deaddrop_proto_rawDescGZIP(), []int{1}
}

func (x *ClientFrame) GetBody() isClientFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientFrame) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ClientFrame) GetPublish() *Envelope {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Publish); ok {
			return x.Publish
		}
	}
	return nil
}

func (x *ClientFrame) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ClientFrame) GetSendOffer() *KeyExchangeOffer {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_SendOffer); ok {
			return x.SendOffer
		}
	}
	return nil
}

func (x *ClientFrame) GetSendAccept() *KeyExchangeAccept {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_SendAccept); ok {
			return x.SendAccept
		}
	}
	return nil
}

type isClientFrame_Body interface {
	isClientFrame_Body()
}

type ClientFrame_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"` // start receiving for a mailbox
}

type ClientFrame_Publish struct {
	Publish *Envelope `protobuf:"bytes,2,opt,name=publish,proto3,oneof"` // send an opaque envelope
}

type ClientFrame_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"` // acknowledge delivery so the bus can drop the blob
}

type ClientFrame_SendOffer struct {
	SendOffer *KeyExchangeOffer `protobuf:"bytes,4,opt,name=send_offer,json=sendOffer,proto3,oneof"` // start a conversation (gated handshake)
}

type ClientFrame_SendAccept struct {
	SendAccept *KeyExchangeAccept `protobuf:"bytes,5,opt,name=send_accept,json=sendAccept,proto3,oneof"` // accept a peer's offer
}

func (*ClientFrame_Subscribe) isClientFrame_Body() {}

func (*ClientFrame_Publish) isClientFrame_Body() {}

func (*ClientFrame_Ack) isClientFrame_Body() {}

func (*ClientFrame_SendOffer) isClientFrame_Body() {}

func (*ClientFrame_SendAccept) isClientFrame_Body() {}

// Gateway -> client.
type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerFrame_Deliver
	//	*ServerFrame_Receipt
	//	*ServerFrame_Error
	//	*ServerFrame_DeliverOffer
	//	*ServerFrame_DeliverAccept
	Body          isServerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_deaddrop_v1_deaddrop_proto_rawDescGZIP(), []int{2}
}

func (x *ServerFrame) GetBody() isServerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerFrame) GetDeliver() *Envelope {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Deliver); ok {
			return x.Deliver
		}
	}
	return nil
}

func (x *ServerFrame) GetReceipt() *Receipt {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Receipt); ok {
			return x.Receipt
		}
	}
	return nil
}

func (x *ServerFrame) GetError() *Error {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerFrame) GetDeliverOffer() *KeyExchangeOffer {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_DeliverOffer); ok {
			return x.DeliverOffer
		}
	}
	return nil
}

func (x *ServerFrame) GetDeliverAccept() *KeyExchangeAccept {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_DeliverAccept); ok {
			return x.DeliverAccept
		}
	}
	return nil
}

type isServerFrame_Body interface {
	isServerFrame_Body()
}

type ServerFrame_Deliver struct {
	Deliver *Envelope `protobuf:"bytes,1,opt,name=deliver,proto3,oneof"` // an opaque envelope addressed to a subscribed mailbox
}

type ServerFrame_Receipt struct {
	Receipt *Receipt `protobuf:"bytes,2,opt,name=receipt,proto3,oneof"` // publish accepted
}

type ServerFrame_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ServerFrame_DeliverOffer struct {
	DeliverOffer *KeyExchangeOffer `protobuf:"bytes,4,opt,name=deliver_offer,json=deliverOffer,proto3,oneof"` // an incoming conversation offer
}

type ServerFrame_DeliverAccept struct {
	DeliverAccept *KeyExchangeAccept `protobuf:"bytes,5,opt,name=deliver_accept,json=deliverAccept,proto3,oneof"` // a peer accepted our offer
}

func (*ServerFrame_Deliver) isServerFrame_Body() {}

func (*ServerFrame_Receipt) isServerFrame_Body() {}

func (*ServerFrame_Error) isServerFrame_Body() {}

func (*ServerFrame_DeliverOffer) isServerFrame_Body() {}

func (*ServerFrame_DeliverAccept) isServerFrame_Body() {}

// The gated mutual key-exchange-and-accept handshake (ADR-009). No message may be sent in a
// conversation until both parties have exchanged KeyPackages and each has accepted.
//
// HONEST LIMIT (ADR-009 residual 1): in this build the exchange is in-app only, relayed by
// the service. There is NO out-of-band verification, so authenticity is trust-on-first-use:
// a hostile or compelled server could substitute keys here (MITM). The `from_signature_key`
// and `key_package` fields are public MLS material, not opaque ciphertext, and the relay can
// read and tamper with them. This is documented and accepted "for now"; do not treat the
// handshake as a defense against the server until OOB verification is re-added.
type KeyExchangeOffer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromSignatureKey []byte                 `protobuf:"bytes,1,opt,name=from_signature_key,json=fromSignatureKey,proto3" json:"from_signature_key,omitempty"` // offerer identity (Ed25519 public key)
	KeyPackage       []byte                 `protobuf:"bytes,2,opt,name=key_package,json=keyPackage,proto3" json:"key_package,omitempty"`                     // offerer's MLS KeyPackage (TLS-serialized)
	ConversationId   string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`         // random, client-generated
	ToRoutingKey     string                 `protobuf:"bytes,4,opt,name=to_routing_key,json=toRoutingKey,proto3" json:"to_routing_key,omitempty"`             // recipient mailbox the gateway relays this to
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KeyExchangeOffer) Reset() {
	*x = KeyExchangeOffer{}
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyExchangeOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchangeOffer) ProtoMessage() {}

func (x *KeyExchangeOffer) ProtoReflect() protoreflect.Message {
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchangeOffer.ProtoReflect.Descriptor instead.
func (*KeyExchangeOffer) Descriptor() ([]byte, []int) {
	return file_deaddrop_v1_deaddrop_proto_rawDescGZIP(), []int{3}
}

func (x *KeyExchangeOffer) GetFromSignatureKey() []byte {
	if x != nil {
		return x.FromSignatureKey
	}
	return nil
}

func (x *KeyExchangeOffer) GetKeyPackage() []byte {
	if x != nil {
		return x.KeyPackage
	}
	return nil
}

func (x *KeyExchangeOffer) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *KeyExchangeOffer) GetToRoutingKey() string {
	if x != nil {
		return x.ToRoutingKey
	}
	return ""
}

type KeyExchangeAccept struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromSignatureKey []byte                 `protobuf:"bytes,1,opt,name=from_signature_key,json=fromSignatureKey,proto3" json:"from_signature_key,omitempty"` // accepter identity (Ed25519 public key)
	KeyPackage       []byte                 `protobuf:"bytes,2,opt,name=key_package,json=keyPackage,proto3" json:"key_package,omitempty"`                     // accepter's MLS KeyPackage (TLS-serialized)
	ConversationId   string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MlsWelcome       []byte                 `protobuf:"bytes,4,opt,name=mls_welcome,json=mlsWelcome,proto3" json:"mls_welcome,omitempty"`         // optional MLS Welcome if the accepter created the group
	ToRoutingKey     string                 `protobuf:"bytes,5,opt,name=to_routing_key,json=toRoutingKey,proto3" json:"to_routing_key,omitempty"` // recipient mailbox the gateway relays this to
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KeyExchangeAccept) Reset() {
	*x = KeyExchangeAccept{}
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyExchangeAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchangeAccept) ProtoMessage() {}

func (x *KeyExchangeAccept) ProtoReflect() protoreflect.Message {
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchangeAccept.ProtoReflect.Descriptor instead.
func (*KeyExchangeAccept) Descriptor() ([]byte, []int) {
	return file_deaddrop_v1_deaddrop_proto_rawDescGZIP(), []int{4}
}

func (x *KeyExchangeAccept) GetFromSignatureKey() []byte {
	if x != nil {
		return x.FromSignatureKey
	}
	return nil
}

func (x *KeyExchangeAccept) GetKeyPackage() []byte {
	if x != nil {
		return x.KeyPackage
	}
	return nil
}

func (x *KeyExchangeAccept) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *KeyExchangeAccept) GetMlsWelcome() []byte {
	if x != nil {
		return x.MlsWelcome
	}
	return nil
}

func (x *KeyExchangeAccept) GetToRoutingKey() string {
	if x != nil {
		return x.ToRoutingKey
	}
	return ""
}

type Subscribe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque mailbox the client wants delivery for. How a client proves it may subscribe to
	// a mailbox without revealing identity is an M3 concern (sealed-sender tokens); M0 carries
	// the field only.
	RoutingKey string `protobuf:"bytes,1,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	// Opaque, stable per-device consumer id for this mailbox (the client sends its bootstrap key,
	// which the gateway already observes on the same connection, so this reveals nothing new). With
	// it, the bus holds each blob until EVERY known consumer of the mailbox has acked it (or the TTL
	// expires) and REDELIVERS un-acked blobs when that consumer re-subscribes, so a device that
	// crashes after a blob was delivered but before it durably processed it sees the blob again
	// instead of losing it forever (at-most-once -> at-least-once per consumer). Empty = a legacy
	// client; it gets the old first-ack-drops semantics.
	ConsumerId    string `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_deaddrop_v1_deaddrop_proto_rawDescGZIP(), []int{5}
}

func (x *Subscribe) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *Subscribe) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     []byte                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_deaddrop_v1_deaddrop_proto_rawDescGZIP(), []int{6}
}

func (x *Ack) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     []byte                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_deaddrop_v1_deaddrop_proto_rawDescGZIP(), []int{7}
}

func (x *Receipt) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=deaddrop.v1.ErrorCode" json:"code,omitempty"`
	// Human-readable, non-sensitive. Never echo payload bytes or routing details here.
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_deaddrop_v1_deaddrop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_deaddrop_v1_deaddrop_proto_rawDescGZIP(), []int{8}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_deaddrop_v1_deaddrop_proto protoreflect.FileDescriptor

const file_deaddrop_v1_deaddrop_proto_rawDesc = "" +
	"\n" +
	"\x1adeaddrop/v1/deaddrop.proto\x12\vdeaddrop.v1\"\x85\x01\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12\x1f\n" +
	"\vrouting_key\x18\x02 \x01(\tR\n" +
	"routingKey\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\rR\n" +
	"ttlSeconds\"\xa9\x02\n" +
	"\vClientFrame\x126\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x16.deaddrop.v1.SubscribeH\x00R\tsubscribe\x121\n" +
	"\apublish\x18\x02 \x01(\v2\x15.deaddrop.v1.EnvelopeH\x00R\apublish\x12$\n" +
	"\x03ack\x18\x03 \x01(\v2\x10.deaddrop.v1.AckH\x00R\x03ack\x12>\n" +
	"\n" +
	"send_offer\x18\x04 \x01(\v2\x1d.deaddrop.v1.KeyExchangeOfferH\x00R\tsendOffer\x12A\n" +
	"\vsend_accept\x18\x05 \x01(\v2\x1e.deaddrop.v1.KeyExchangeAcceptH\x00R\n" +
	"sendAcceptB\x06\n" +
	"\x04body\"\xb5\x02\n" +
	"\vServerFrame\x121\n" +
	"\adeliver\x18\x01 \x01(\v2\x15.deaddrop.v1.EnvelopeH\x00R\adeliver\x120\n" +
	"\areceipt\x18\x02 \x01(\v2\x14.deaddrop.v1.ReceiptH\x00R\areceipt\x12*\n" +
	"\x05error\x18\x03 \x01(\v2\x12.deaddrop.v1.ErrorH\x00R\x05error\x12D\n" +
	"\rdeliver_offer\x18\x04 \x01(\v2\x1d.deaddrop.v1.KeyExchangeOfferH\x00R\fdeliverOffer\x12G\n" +
	"\x0edeliver_accept\x18\x05 \x01(\v2\x1e.deaddrop.v1.KeyExchangeAcceptH\x00R\rdeliverAcceptB\x06\n" +
	"\x04body\"\xb0\x01\n" +
	"\x10KeyExchangeOffer\x12,\n" +
	"\x12from_signature_key\x18\x01 \x01(\fR\x10fromSignatureKey\x12\x1f\n" +
	"\vkey_package\x18\x02 \x01(\fR\n" +
	"keyPackage\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12$\n" +
	"\x0eto_routing_key\x18\x04 \x01(\tR\ftoRoutingKey\"\xd2\x01\n" +
	"\x11KeyExchangeAccept\x12,\n" +
	"\x12from_signature_key\x18\x01 \x01(\fR\x10fromSignatureKey\x12\x1f\n" +
	"\vkey_package\x18\x02 \x01(\fR\n" +
	"keyPackage\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x1f\n" +
	"\vmls_welcome\x18\x04 \x01(\fR\n" +
	"mlsWelcome\x12$\n" +
	"\x0eto_routing_key\x18\x05 \x01(\tR\ftoRoutingKey\"M\n" +
	"\tSubscribe\x12\x1f\n" +
	"\vrouting_key\x18\x01 \x01(\tR\n" +
	"routingKey\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\"$\n" +
	"\x03Ack\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\"(\n" +
	"\aReceipt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\"K\n" +
	"\x05Error\x12*\n" +
	"\x04code\x18\x01 \x01(\x0e2\x16.deaddrop.v1.ErrorCodeR\x04code\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail*\x8f\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ERROR_CODE_MALFORMED\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_TOO_LARGE\x10\x02\x12\x19\n" +
	"\x15ERROR_CODE_RATE_LIMIT\x10\x03\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x04BBZ@github.com/deaddrop/gateway/internal/wire/deaddrop/v1;deaddropv1b\x06proto3"

var (
	file_deaddrop_v1_deaddrop_proto_rawDescOnce sync.Once
	file_deaddrop_v1_deaddrop_proto_rawDescData []byte
)

func file_deaddrop_v1_deaddrop_proto_rawDescGZIP() []byte {
	file_deaddrop_v1_deaddrop_proto_rawDescOnce.Do(func() {
		file_deaddrop_v1_deaddrop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deaddrop_v1_deaddrop_proto_rawDesc), len(file_deaddrop_v1_deaddrop_proto_rawDesc)))
	})
	return file_deaddrop_v1_deaddrop_proto_rawDescData
}

var file_deaddrop_v1_deaddrop_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_deaddrop_v1_deaddrop_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_deaddrop_v1_deaddrop_proto_goTypes = []any{
	(ErrorCode)(0),            // 0: deaddrop.v1.ErrorCode
	(*Envelope)(nil),          // 1: deaddrop.v1.Envelope
	(*ClientFrame)(nil),       // 2: deaddrop.v1.ClientFrame
	(*ServerFrame)(nil),       // 3: deaddrop.v1.ServerFrame
	(*KeyExchangeOffer)(nil),  // 4: deaddrop.v1.KeyExchangeOffer
	(*KeyExchangeAccept)(nil), // 5: deaddrop.v1.KeyExchangeAccept
	(*Subscribe)(nil),         // 6: deaddrop.v1.Subscribe
	(*Ack)(nil),               // 7: deaddrop.v1.Ack
	(*Receipt)(nil),           // 8: deaddrop.v1.Receipt
	(*Error)(nil),             // 9: deaddrop.v1.Error
}
var file_deaddrop_v1_deaddrop_proto_depIdxs = []int32{
	6,  // 0: deaddrop.v1.ClientFrame.subscribe:type_name -> deaddrop.v1.Subscribe
	1,  // 1: deaddrop.v1.ClientFrame.publish:type_name -> deaddrop.v1.Envelope
	7,  // 2: deaddrop.v1.ClientFrame.ack:type_name -> deaddrop.v1.Ack
	4,  // 3: deaddrop.v1.ClientFrame.send_offer:type_name -> deaddrop.v1.KeyExchangeOffer
	5,  // 4: deaddrop.v1.ClientFrame.send_accept:type_name -> deaddrop.v1.KeyExchangeAccept
	1,  // 5: deaddrop.v1.ServerFrame.deliver:type_name -> deaddrop.v1.Envelope
	8,  // 6: deaddrop.v1.ServerFrame.receipt:type_name -> deaddrop.v1.Receipt
	9,  // 7: deaddrop.v1.ServerFrame.error:type_name -> deaddrop.v1.Error
	4,  // 8: deaddrop.v1.ServerFrame.deliver_offer:type_name -> deaddrop.v1.KeyExchangeOffer
	5,  // 9: deaddrop.v1.ServerFrame.deliver_accept:type_name -> deaddrop.v1.KeyExchangeAccept
	0,  // 10: deaddrop.v1.Error.code:type_name -> deaddrop.v1.ErrorCode
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_deaddrop_v1_deaddrop_proto_init() }
func file_deaddrop_v1_deaddrop_proto_init() {
	if File_deaddrop_v1_deaddrop_proto != nil {
		return
	}
	file_deaddrop_v1_deaddrop_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientFrame_Subscribe)(nil),
		(*ClientFrame_Publish)(nil),
		(*ClientFrame_Ack)(nil),
		(*ClientFrame_SendOffer)(nil),
		(*ClientFrame_SendAccept)(nil),
	}
	file_deaddrop_v1_deaddrop_proto_msgTypes[2].OneofWrappers = []any{
		(*ServerFrame_Deliver)(nil),
		(*ServerFrame_Receipt)(nil),
		(*ServerFrame_Error)(nil),
		(*ServerFrame_DeliverOffer)(nil),
		(*ServerFrame_DeliverAccept)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deaddrop_v1_deaddrop_proto_rawDesc), len(file_deaddrop_v1_deaddrop_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deaddrop_v1_deaddrop_proto_goTypes,
		DependencyIndexes: file_deaddrop_v1_deaddrop_proto_depIdxs,
		EnumInfos:         file_deaddrop_v1_deaddrop_proto_enumTypes,
		MessageInfos:      file_deaddrop_v1_deaddrop_proto_msgTypes,
	}.Build()
	File_deaddrop_v1_deaddrop_proto = out.File
	file_deaddrop_v1_deaddrop_proto_goTypes = nil
	file_deaddrop_v1_deaddrop_proto_depIdxs = nil
}
